blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Community Chat (Telegram)
    url: https://t.me/VivaBite_Community
    about: For questions or general discussion, join our Telegram community.

  - name: ğŸ¦ Twitter / X
    url: https://x.com/VivaBitePub
    about: Follow us on Twitter for updates or to DM the team

  - name: âœ‰ï¸ Email Support
    url: mailto:support@vivabite.life
    about: For sensitive or account-related matters, contact us by email
